const rawExamData = [
    // ==========================================
    // BÀI ĐỌC SỐ 1: La Gardina Mall
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>Leasing Opportunities</b><br><br>La Gardina Mall offers a unique shopping experience in a beautiful setting of landscaped gardens, courtyards, and fountains. The mall features retail shops that range from well-known chain stores to one-of-a-kind boutiques, as well as a large variety of restaurants and cafés.<br><br>With 300,000 square meters of pedestrian-only retail space, La Gardina Mall attracts more than four million visitors per year. It is a shopping and dining destination for local Bay Shore residents and tourists alike.<br><br>If you would like more information about leasing retail or restaurant space at La Gardina, please contact Cecilia Goncalves, our Leasing Administrator, at cgoncalves@lagardina.com. While most of our space is occupied by long-term lessees, a limited number of seasonal contracts (four months minimum) are available.",
            
            "<b>E-mail</b><br><b>To:</b> Cecilia Goncalves &lt;cgoncalves@lagardina.com&gt;<br><b>From:</b> Marco Sabatini &lt;msabatini@sabatinileather.com&gt;<br><b>Date:</b> 25 March<br><b>Subject:</b> Retail space<br><b>Attachment:</b> List of products<br><br>Dear Ms. Goncalves:<br><br>As owner of Sabatini Leather Goods, I would like to express interest in a short-term leasing opportunity at La Gardina Mall.<br><br>Sabatini Leather Goods is a small company that manufactures and sells souvenir handbags and wallets. Our high-quality leather products are imprinted with the name of the tourist destination where they are sold. I have attached some images of our best-selling items from our most recent temporary shop in Glastonbury, where we had our best sales performance in the company’s history. We have sold our products in 24 different locations so far, all with great success.<br><br>We have been looking for a place in Bay Shore for a while, and La Gardina Mall seems to be a good fit. We would like a space of about 150 square meters for a three-month period over the summer tourism season. Could you please call me at 555-0125 so that we can discuss this matter further?<br><br>Respectfully,<br>Marco Sabatini"
        ],
        questions: [
            { text: "What is suggested about La Gardina Mall?", options: { A: "It is located in Bay Shore.", B: "It is open only in the summer.", C: "It recently added many new shops.", D: "It features mainly fashion boutiques." }, correct: "A", explanation: "Thông tin nằm ở đoạn 2 của quảng cáo: 'destination for local Bay Shore residents...'." },
            { text: "In the advertisement, the word 'occupied' in paragraph 3, line 3, is closest in meaning to", options: { A: "filled", B: "captured", C: "kept busy", D: "made steady" }, correct: "A", explanation: "Từ 'occupied' ở đây mang nghĩa là không gian đã được lấp đầy / cho thuê hết (filled)." },
            { text: "What is the main purpose of the e-mail?", options: { A: "To promote a new botanical garden", B: "To profile a popular company", C: "To inquire about a potential business deal", D: "To ask about job opportunities at a mall" }, correct: "C", explanation: "Marco Sabatini viết email để hỏi về cơ hội thuê mặt bằng ngắn hạn." },
            { text: "What is indicated about Sabatini Leather Goods products?", options: { A: "They are sold online.", B: "They are often discounted.", C: "They are marketed to tourists.", D: "They are manufactured in Glastonbury." }, correct: "C", explanation: "Đoạn 2 của email đề cập công ty bán 'souvenir handbags' được in tên các địa điểm du lịch (marketed to tourists)." },
            { text: "What will Mr. Sabatini and Ms. Goncalves most likely have to negotiate?", options: { A: "The location of a store", B: "The length of a contract", C: "The size of a retail space", D: "The cost of a monthly lease" }, correct: "B", explanation: "Quảng cáo yêu cầu hợp đồng tối thiểu 4 tháng, nhưng Marco lại muốn thuê trong 3 tháng. Họ sẽ phải đàm phán về thời hạn hợp đồng." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 2: Contiera Corporation
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>E-mail</b><br><b>To:</b> Management Team<br><b>From:</b> Fiona Watson<br><b>Date:</b> March 19<br><b>Subject:</b> Spring meeting<br><b>Attachment:</b> Final Agenda<br><br>Dear Colleagues,<br><br>This is a reminder that Contiera Corporation’s spring management meeting is scheduled for 9 A.M. tomorrow. The final agenda is attached. Please note that I have added an item to the original meeting agenda. Mai Tran, our publications supervisor, wants to update everyone on this season’s product line. She should not take more than twenty minutes.<br><br>To prepare for the meeting, please review our most recent marketing plan so that we all have a clear idea of our goals for the quarter. It would also help if each of you brought copies of your latest budget report and projected cost estimates for next quarter.<br><br>I look forward to seeing you tomorrow.<br><br>Fiona Watson",
            
            "<b>Spring Management Meeting—Final Agenda</b><br><br><b>Date and Time:</b> March 20, 9 A.M.<br><b>Location:</b> Conference Room 2<br><br><b>Topic:</b> Community events<br><b>Description:</b> Learn about local outreach opportunities<br><b>Leader:</b> Paul Ranier, president of the Arborville Business Association<br><br><b>Topic:</b> Budget review<br><b>Description:</b> Discuss department budgets<br><b>Leader:</b> Fiona Watson<br><br><b>Topic:</b> Online advertising<br><b>Description:</b> Review cost of Web ads / Analyze areas for growth<br><b>Leader:</b> Marcia Dover<br><br><b>Topic:</b> Web site updates<br><b>Description:</b> Present recent changes to ski-apparel page / Demonstrate new content management software<br><b>Leader:</b> Barry Callahan<br><br><b>Topic:</b> Print publications<br><b>Description:</b> Review final changes to spring sportswear catalog<br><b>Leader:</b> Mai Tran"
        ],
        questions: [
            { text: "In the e-mail, what does Ms. Watson imply about the meeting?", options: { A: "Some clients will be attending it.", B: "A recently hired supervisor will be leading it.", C: "It will take more time than originally planned.", D: "Its location has been changed." }, correct: "C", explanation: "Trong email, cô Watson nói 'I have added an item... She should not take more than twenty minutes.' -> Cuộc họp sẽ dài hơn dự kiến." },
            { text: "What item on the agenda is new?", options: { A: "Community events", B: "Online advertising", C: "Web site updates", D: "Print publications" }, correct: "D", explanation: "Người được thêm vào là Mai Tran. Nhìn sang lịch trình, Mai Tran phụ trách mục 'Print publications'." },
            { text: "What does Ms. Watson ask people to bring to the meeting?", options: { A: "Updated financial documents", B: "A list of new hires", C: "A copy of the agenda", D: "Revised vendor contracts" }, correct: "A", explanation: "Email yêu cầu mang 'budget report and projected cost estimates' -> tương đương tài liệu tài chính (financial documents)." },
            { text: "What does the agenda indicate about Mr. Ranier?", options: { A: "He teaches a course in online advertising.", B: "He will be joining the meeting by telephone.", C: "He used to work with Ms. Watson.", D: "He represents a local organization." }, correct: "D", explanation: "Paul Ranier là 'president of the Arborville Business Association' -> đại diện cho tổ chức địa phương." },
            { text: "What does Contiera Corporation most likely sell?", options: { A: "Books and magazines", B: "Gardening supplies", C: "Athletic clothing", D: "Computer software" }, correct: "C", explanation: "Trong lịch trình nhắc đến 'ski-apparel page' và 'sportswear catalog' -> công ty bán đồ thể thao." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 3: Plumsted Aynes
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>E-mail</b><br><b>To:</b> Dennis Maki<br><b>From:</b> Nigella Smith<br><b>Date:</b> Thursday, November 8, 2:15 P.M.<br><b>Subject:</b> Update<br><br>Dennis:<br><br>The heads of accounting and sales have chosen the finalists for the job openings in their departments here at Plumsted Aynes. Susan Tsai would like to invite Marco Garcia and Danielle Jenkins to return for second interviews for the accounting position, and Rajesh Kapoor wants to invite Melanie Yu for a second interview for the medical sales position.<br><br>I would like you to call the finalists, schedule interviews with them, and then make lunch arrangements accordingly. Keep in mind that Susan will be out of the office next week for a conference.<br><br>Thank you for your assistance with this search so far. I’m especially grateful that you were able to work on a short deadline when I asked you to set up the initial interviews.<br><br>Regards,<br>Nigella Smith<br>Human Resources Director",
            
            "<b>E-mail</b><br><b>To:</b> Nigella Smith<br><b>From:</b> Dennis Maki<br><b>Date:</b> Thursday, November 8, 3:52 P.M.<br><b>Subject:</b> RE: Update<br><br>Nigella:<br><br>I called the three finalists. As it turns out, this afternoon Melanie Yu accepted a job offer with another pharmaceutical firm—our competitor Granquist. I informed Rajesh about this development and he said he hopes to find a suitable replacement.<br><br>I have confirmed an interview for Mr. Garcia on Tuesday, November 20. I also made arrangements with our regular catering company for lunch here. Unfortunately, Ms. Jenkins was recently hospitalized, so I’m leaving any further decision about her interview with you.<br><br>Dennis Maki<br>Administrative Associate"
        ],
        questions: [
            { text: "What is one purpose of the first e-mail?", options: { A: "To announce a job opening", B: "To make an offer to a job applicant", C: "To request that applicants be contacted", D: "To check a job candidate's references" }, correct: "C", explanation: "Trong email đầu tiên, Nigella viết: 'I would like you to call the finalists, schedule interviews...' -> Yêu cầu liên lạc với ứng viên." },
            { text: "What type of company most likely is Plumsted Aynes?", options: { A: "An accounting firm", B: "A medical clinic", C: "A caterer", D: "A pharmaceutical company" }, correct: "D", explanation: "Ở email thứ 2, Dennis đề cập đến đối thủ cạnh tranh là hãng dược 'Granquist'. Suy ra công ty của họ cũng là công ty dược." },
            { text: "What is suggested about Ms. Jenkins?", options: { A: "She has visited Plumsted Aynes before.", B: "She will be interviewed by Ms. Smith.", C: "She previously worked for Granquist.", D: "She is interested in a sales position." }, correct: "A", explanation: "Email đầu tiên nhắc đến việc mời ứng viên quay lại phỏng vấn vòng 2 ('return for second interviews'). Tức là cô ấy đã từng đến công ty trước đây rồi." },
            { text: "What will Mr. Kapoor most likely do?", options: { A: "Meet with Mr. Garcia", B: "Attend a conference", C: "Make reservations at a restaurant", D: "Select a new candidate to interview" }, correct: "D", explanation: "Dennis báo cáo ứng viên của Rajesh Kapoor đã nhận việc khác, và ông ấy hy vọng tìm được người thay thế -> Ông ấy sẽ chọn ứng viên mới." },
            { text: "What was Mr. Maki NOT able to do?", options: { A: "Order food to be delivered", B: "Schedule all the appointments within a given time frame", C: "Have a conversation with Ms. Yu", D: "Assist Ms. Smith with setting up the initial interviews" }, correct: "B", explanation: "Dennis được yêu cầu lên lịch cho cả 3 người, nhưng anh ấy chỉ chốt được lịch cho 1 người. Nên anh ấy KHÔNG THỂ lên lịch cho TẤT CẢ các cuộc hẹn." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 4: Lellar Manufacturing
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>MEMO</b><br><b>To:</b> All Staff<br><b>From:</b> Shondra Brown, Director of Benefits<br><b>Date:</b> August 4<br><b>Re:</b> Wellness Classes<br><br>In the interest of promoting a healthy and productive workforce, Lellar Manufacturing will begin offering monthly wellness classes. While participation is not required, we do hope that everyone will take advantage of this opportunity. Part- and full-time regular employees are eligible for these classes at no cost. All other workers and trainees will be required to pay a small enrollment fee.<br><br>Local nurses from Union City Hospital will run the classes on-site, so you do not have to travel anywhere. Classes will be held the first Friday morning of each month, and the class topics will change each month. The class topics in order, starting in September and going through December, will be as follows: Easy Stretching, Good Food Choices, Tips for Better Sleep, and Starting an Exercise Group.<br><br>Supervisor approval is necessary. The first step is to complete a class request form and send it to the Benefits Department. If you have any questions, contact our benefits counselors Don Herrell at ext. 249 or Leah Katzen at ext. 199.",
            
            "<b>Lellar Manufacturing</b><br><b>WELLNESS CLASS REQUEST FORM</b><br><br><b>Name:</b> Alfredo De Santos<br><b>Title:</b> Production Trainee<br><b>Name/Title of Immediate Supervisor:</b> Galen Sanders, Production Manager<br><b>Requested Class Date:</b> September 2<br><b>Enrollment Fee Paid:</b> ✓<br><b>Received by Benefits Counselor:</b> Leah Katzen"
        ],
        questions: [
            { text: "What is the purpose of the memo?", options: { A: "To explain a new requirement", B: "To inform staff about a benefit", C: "To suggest a process improvement", D: "To introduce cost-saving measures" }, correct: "B", explanation: "Memo thông báo về 'monthly wellness classes' (lớp học sức khỏe hàng tháng). Đây là việc thông báo cho nhân viên về một phúc lợi." },
            { text: "Where will a company activity take place?", options: { A: "At Lellar Manufacturing", B: "At Union City Hospital", C: "At a local doctor's office", D: "At a nearby production facility" }, correct: "A", explanation: "Đoạn 2 của Memo ghi rõ: 'run the classes on-site' (điều hành lớp học tại chỗ/ngay tại công ty). Công ty này là Lellar Manufacturing." },
            { text: "What topic will be covered in September?", options: { A: "Easy Stretching", B: "Good Food Choices", C: "Tips for Better Sleep", D: "Starting an Exercise Group" }, correct: "A", explanation: "Memo liệt kê các chủ đề bắt đầu từ tháng 9 lần lượt là: Easy Stretching, Good Food Choices... Vậy tháng 9 là Easy Stretching." },
            { text: "Why has Mr. De Santos paid a fee?", options: { A: "He returned his training materials late.", B: "He needs to replace some training items.", C: "He is not a regular employee.", D: "He requested an extra class." }, correct: "C", explanation: "Trong biểu mẫu, chức danh của Alfredo là 'Production Trainee'. Memo quy định những người không phải nhân viên chính thức phải trả phí." },
            { text: "Who must provide an approval?", options: { A: "Ms. Brown", B: "Mr. Herrell", C: "Ms. Katzen", D: "Mr. Sanders" }, correct: "D", explanation: "Memo yêu cầu cần sự phê duyệt của người quản lý (Supervisor). Trong biểu mẫu, quản lý trực tiếp của Alfredo là Galen Sanders." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 5: Western States Milling
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>From:</b> Hiroaki Yoneya &lt;hyoneya@westernstatesmilling.net&gt;<br><b>To:</b> Clay Crosby &lt;ccrosby@westernstatesmilling.net&gt;<br><b>Date:</b> June 1<br><b>Subject:</b> Baseball night<br><br>Clay,<br><br>You may remember that we recently discussed ideas for an outing for the employees and their families. I think the best idea is to go to a baseball game. I have always enjoyed taking my family to see the Billington Buffaloes, our local team. You might have noticed that several of the photos in my office were taken at the stadium! And since I usually see other staff members at the games, I think this will appeal to most of our group.<br><br>Would you please set this up for June 28? I believe it can all be done online if you prefer. By my calculations, we will need 45 tickets in total, but please double-check this number. Also, I would like food to be provided. Let’s limit our cost to under $20 per person and make sure the seating is covered just in case the weather is poor. Please send me the details as soon as the tickets are purchased.<br><br>Thanks,<br>Hiroaki Yoneya, Associate Manager<br>Western States Milling, Inc.",
            
            "<table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: center; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Group Areas</th><th style='background-color: #f0f0f0;'>Maximum Capacity</th><th style='background-color: #f0f0f0;'>Price</th><th style='background-color: #f0f0f0;'>Covered Seating</th></tr><tr><td>Home Run Pavilion</td><td>60 people</td><td>$17 per person</td><td>Yes</td></tr><tr><td>First Base Dugout Den</td><td>50 people</td><td>$19 per person</td><td>No</td></tr><tr><td>North Side Party Deck</td><td>60 people</td><td>$25 per person</td><td>No</td></tr><tr><td>Deluxe Suites</td><td>50 people</td><td>$30 per person</td><td>Yes</td></tr></table><b>Group Ticket Policies</b><br><br><ul style='margin-left: 20px; line-height: 1.6;'><li>Each group member in the Home Run Pavilion, First Base Dugout Den, and North Side Party Deck areas will receive a hot dog, chips, and a soda. The Deluxe Suites include an all-you-can-eat buffet for each guest.</li><li>Each group will receive a special visit from the mascot, Bobby Buffalo.</li><li>Groups will be welcomed to the stadium over the announcement system.</li><li>Everyone in the group will receive 10% off team merchandise (on game day only).</li><li>A 25% deposit is required when booking. The remaining balance is due no later than two weeks in advance of the date booked. Tickets will be mailed when the balance is paid.</li><li>Please call the box office at (406) 555-0192 with any questions.</li></ul>"
        ],
        questions: [
            { text: "What is the purpose of the e-mail?", options: { A: "To ask an employee to arrange an event", B: "To discuss a baseball team's request", C: "To inform employees about ticket prices", D: "To solicit suggestions for a company outing" }, correct: "A", explanation: "Mục đích của Hiroaki Yoneya là yêu cầu Clay Crosby sắp xếp buổi đi xem bóng chày: 'Would you please set this up for June 28?'." },
            { text: "What is indicated about Mr. Yoneya?", options: { A: "He found an error on the team's Web site.", B: "He regularly attends baseball games.", C: "He wants to change the date of an event.", D: "He recently moved to Billington." }, correct: "B", explanation: "Anh ấy viết 'I have always enjoyed taking my family to see...' và có nhiều ảnh chụp ở sân vận động -> Anh ấy thường xuyên đi xem bóng chày." },
            { text: "What section of the stadium is best for the Western States Milling staff?", options: { A: "Home Run Pavilion", B: "First Base Dugout Den", C: "North Side Party Deck", D: "Deluxe Suites" }, correct: "A", explanation: "Yêu cầu của Hiroaki là: 45 vé, giá dưới $20/người, có đồ ăn và mái che. Đối chiếu với bảng, khu 'Home Run Pavilion' chứa được 60 người, giá $17 (dưới 20), và Covered Seating: Yes. Lựa chọn này thoả mãn mọi điều kiện." },
            { text: "What is NOT an additional benefit available to group ticket holders?", options: { A: "A visit from Bobby Buffalo", B: "A welcome announcement", C: "A discount on merchandise", D: "A group photograph" }, correct: "D", explanation: "Chính sách vé nhóm có liệt kê: linh vật Bobby ghé thăm, chào mừng qua loa, giảm giá 10% đồ lưu niệm. Không có nhắc đến việc chụp ảnh nhóm." },
            { text: "According to the Web page, what must Mr. Crosby do in order to make a reservation?", options: { A: "Make a deposit", B: "Have his supervisor sign a form", C: "Call the box office", D: "Complete an online ticket request" }, correct: "A", explanation: "Trong danh sách chính sách có ghi rõ: 'A 25% deposit is required when booking.' (Bắt buộc phải đặt cọc 25% khi đặt vé)." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 6: HJP Transport Solutions
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>HJP Transport Solutions, Ltd.</b><br><b>Powell Internship Programme</b><br><br>HJP Transport Solutions, Ltd., headquartered in London, seeks university students to fill ten intern positions in its Powell Internship Programme (PIP). Interns will be placed in one of HJP’s three regional offices: Birmingham, Manchester, or Bristol. Applicants should e-mail a statement of interest and résumé to pip@hjp.co.uk by 31 March. Successful candidates will have the honour of being the first recipients of the Powell Internship.<br><br><b>Background:</b><br>PIP is the initiative of Tristan Powell, who wanted to honour the ingenuity of Henry J. Powell, the founder of HJP Transport Solutions, Ltd. The programme seeks to inspire young engineering students to follow in Henry J. Powell’s footsteps and propose and develop innovative solutions to shipping and transport problems. Having earned his doctorate degree in engineering, Henry J. Powell went on to found HJP Transport Solutions, Ltd. Over time, he built the company into a successful, internationally renowned business. Having served four decades as company president, he retired last year and was succeeded by his son, Tristan.",
            
            "<b>To:</b> Joseph Chen &lt;jchen@sunnydale.ac.uk&gt;<br><b>From:</b> Padma Vithana &lt;pvithana@hjp.co.uk&gt;<br><b>Date:</b> 25 April<br><b>Subject:</b> Information<br><br>Dear Mr. Chen,<br><br>Thank you for promptly returning the paperwork relevant to your internship. You will receive your intern packet within a week.<br><br>As for your inquiry about housing, I appreciate your concern that the two-hour train ride from London to your assigned location makes for an arduous daily commute. Regrettably, HJP does not provide accommodations for interns. I suggest that you contact Mr. Daniel Anders who is in charge of the internship program in our Bristol office. He has lived in the city for many years and presumably will have some advice about housing options there. Good luck, and I hope you will enjoy working at HJP.<br><br>Sincerely,<br>Padma Vithana<br>Director of Recruiting, HJP Transport Solutions, Ltd."
        ],
        questions: [
            { text: "What is the purpose of the notice?", options: { A: "To list volunteer opportunities at a company", B: "To describe the history of a company", C: "To advertise a company’s new program", D: "To announce the retirement of a company’s president" }, correct: "C", explanation: "Đoạn 1 giới thiệu và quảng cáo về chương trình thực tập mới PIP: 'seeks university students to fill ten intern positions...'." },
            { text: "Who is Tristan Powell?", options: { A: "The founder of a business", B: "The head of a company", C: "A university instructor", D: "An internship candidate" }, correct: "B", explanation: "Cuối đoạn 1 ghi rõ Henry Powell đã nghỉ hưu và được kế nhiệm bởi con trai là Tristan. Vậy Tristan hiện là người đứng đầu công ty." },
            { text: "What is one reason for Ms. Vithana's e-mail?", options: { A: "To congratulate Mr. Chen", B: "To inquire about a problem", C: "To send Mr. Chen paperwork", D: "To answer a question" }, correct: "D", explanation: "Padma Vithana viết email để trả lời thắc mắc của Chen về chỗ ở: 'As for your inquiry about housing...'." },
            { text: "What is true about Mr. Chen?", options: { A: "He has worked with Mr. Anders in the past.", B: "He requested help with a project.", C: "He is an engineering student.", D: "He is transferring to a different office" }, correct: "C", explanation: "Chương trình PIP tìm kiếm 'young engineering students' (sinh viên kỹ thuật). Vì Chen được nhận vào thực tập, anh ấy là một sinh viên kỹ thuật." },
            { text: "Where will Mr. Chen be working?", options: { A: "In Birmingham", B: "In Bristol", C: "In London", D: "In Manchester" }, correct: "B", explanation: "Padma khuyên Chen liên hệ Daniel Anders - người phụ trách ở văn phòng Bristol, vì ông ấy sống ở đó và có thể tư vấn về chỗ ở. Vậy Chen được phân công làm việc tại Bristol." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 7: Knight Museum of Art
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>To:</b> Hyo-Jung Cho<br><b>From:</b> Julian Katz<br><b>Date:</b> 14 June<br><b>Subject:</b> Information<br><br>Dear Ms. Cho:<br><br>Since you were away last week, you might not yet know all the details of the situation with the Web site. Shannon Gehring, our Web designer, was in the middle of revising the site when a severe thunderstorm hit our area. Our servers were struck by lightning and sustained some damage. While they were being repaired, the museum’s Web site was down for two days.<br><br>I know you are planning to send an e-mail to members today, asking them to help us meet a fund-raising goal by 30 June, the end of our fiscal year. Our site is back online now, and includes a new comments page that can be used for this fund-raising event. Please let me know if you need additional information.<br><br>Sincerely,<br>Julian Katz<br>IT Coordinator<br>Knight Museum of Art",
            
            "<b>http://www.knightmuseumofart.ca/comments</b><br><br><b>14 June</b><br><br>I am such a big fan of the Knight Museum! I have been taking advantage of some of the museum’s wonderful programs. The recent series of watercolor painting classes with local artist Leroy Davis was terrific. This experience with watercolors will help me appreciate the museum’s current exhibition of Japanese watercolor paintings even more; I’m looking forward to taking a tour of the exhibition next week.<br><br>I already contribute as a museum member, but I just made an additional donation online today after I received a fund-raising e-mail from the museum’s director. It was easy to access the Web site, although I had trouble last week. I hope others will support the museum by contributing before the 30 June deadline. The Knight Museum’s programming is worth it.<br><br>—Brenda Sanz"
        ],
        questions: [
            { text: "Why did Mr. Katz contact Ms. Cho?", options: { A: "To introduce a new employee", B: "To provide an update", C: "To request details about an event", D: "To ask for assistance" }, correct: "B", explanation: "Julian Katz viết email để cập nhật tình hình website bị hỏng và đã được sửa xong." },
            { text: "In the e-mail, the word 'meet' in paragraph 2, line 1, is closest in meaning to", options: { A: "connect", B: "fulfill", C: "encounter", D: "assemble" }, correct: "B", explanation: "Từ 'meet' trong cụm 'meet a fund-raising goal' mang nghĩa là đạt được, hoàn thành mục tiêu (tương đương với 'fulfill')." },
            { text: "Who is Ms. Cho?", options: { A: "The museum director", B: "The IT coordinator", C: "A Web designer", D: "A local artist" }, correct: "A", explanation: "Julian nhắc đến việc Cho sẽ gửi email kêu gọi quyên góp. Trong bình luận, Brenda Sanz nói đã nhận được email quyên góp từ 'museum's director' (Giám đốc bảo tàng). Vậy Cho chính là giám đốc." },
            { text: "What is Ms. Sanz eager to do?", options: { A: "Help with the Web site", B: "Lead tours for members", C: "Enroll in an art class", D: "Attend an exhibition" }, correct: "D", explanation: "Brenda viết: 'I’m looking forward to taking a tour of the exhibition next week.' -> Cô ấy háo hức muốn đi xem triển lãm." },
            { text: "What does Ms. Sanz suggest in her comment?", options: { A: "She made a donation before the end of the fiscal year.", B: "She has visited Japan.", C: "She recently accessed the museum's online art collection.", D: "She purchased a painting by Leroy Davis." }, correct: "A", explanation: "Brenda nói 'I just made an additional donation online today... before the 30 June deadline.' -> Theo email của Julian, 30/6 cũng chính là ngày kết thúc năm tài chính." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 8: Quipwerx Support
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>Quipwerx Support Request Form</b><br><br>Complete and submit this form to create a support ticket number. We will e-mail you a response within 24 hours.<br><br><b>Name:</b> Agnes Kowalski<br><b>Company:</b> Alexsy Corporation<br><b>E-mail Address:</b> akowalski@alexsycorp.net<br><b>Subject:</b> Web-conferencing issues<br><br><b>Please describe the problem you are experiencing.</b><br>We started using your Web-conferencing software in June and have been pleased with it overall. Yesterday, however, we had several interruptions in service during an important training session. In the middle of our meeting, the screen suddenly went black and a notice appeared stating, “Quipwerx is down for maintenance.” Several employees were calling in from overseas, and after this notice appeared multiple times, we decided to reschedule. Is there a way for you to inform us of your maintenance schedule in advance? If not, I will probably terminate my membership. I must be confident that I can use your product anytime I need it.",
            
            "<b>To:</b> Agnes Kowalski &lt;akowalski@alexsycorp.net&gt;<br><b>From:</b> Quipwerx Support &lt;support@quipwerxsoftware.com&gt;<br><b>Date:</b> July 29<br><b>Subject:</b> Ticket 000125659 — Web-Conferencing Issues<br><br>Dear Ms. Kowalski,<br><br>Thank you for contacting us with your concerns. The issue you had this past Wednesday was caused by servers that crashed due to a database communication issue. We could not anticipate this problem, so we were unable to warn customers in advance. I assure you that this type of occurrence is very rare.<br><br>In light of your comments, we have decided to reword our alert message from “down for maintenance” to “experiencing technical difficulties.” That way customers will know the problem is due to unforeseen circumstances rather than routine maintenance. As a matter of fact, our software is hardly ever down for maintenance. When we work on an upgrade, the software is unavailable for just a few minutes, if at all.<br><br>We regret the inconvenience this has caused you and are truly grateful for your feedback. In appreciation of your business, we will be waiving the service fee on your company account for this month.<br><br>Sincerely,<br>Cindy Trautman<br>Quipwerx Support"
        ],
        questions: [
            { text: "What does Ms. Kowalski request on the online form?", options: { A: "A membership cancellation", B: "A maintenance calendar", C: "A call from customer support", D: "A new time for a training session" }, correct: "B", explanation: "Agnes Kowalski hỏi: 'Is there a way for you to inform us of your maintenance schedule in advance?' -> Cô ấy muốn biết lịch bảo trì trước." },
            { text: "What is suggested about Ms. Kowalski?", options: { A: "She used to work for Quipwerx.", B: "She joined Alexsy Corporation in June.", C: "She uses Web-conferencing software regularly.", D: "She conducts training sessions every Wednesday" }, correct: "C", explanation: "Cô ấy nói 'I must be confident that I can use your product anytime I need it' và hài lòng với dịch vụ từ tháng 6, cho thấy cô ấy sử dụng phần mềm này rất thường xuyên." },
            { text: "What is Ms. Kowalski's complaint regarding Quipwerx conferencing software?", options: { A: "It does not serve her current purposes.", B: "It is incompatible with her computer.", C: "It is unreliable.", D: "It cannot be used by her overseas clients." }, correct: "C", explanation: "Màn hình đột ngột đen và báo lỗi giữa cuộc họp quan trọng, khiến cô ấy phải đặt lại lịch -> Phàn nàn rằng phần mềm này không đáng tin cậy (unreliable)." },
            { text: "What does Ms. Trautman say Quipwerx will change?", options: { A: "Its malfunction message", B: "Its customer agreement", C: "Its Web-conferencing software", D: "Its maintenance schedule" }, correct: "A", explanation: "Cindy cho biết họ sẽ đổi thông báo từ 'down for maintenance' thành 'experiencing technical difficulties' -> Thay đổi thông báo báo lỗi." },
            { text: "What is indicated about Alexsy Corporation?", options: { A: "It services its system regularly.", B: "It hires new staff every week.", C: "It recently upgraded its software.", D: "It pays a monthly fee to Quipwerx." }, correct: "D", explanation: "Cindy nói 'we will be waiving the service fee on your company account for this month' -> Alexsy thường phải trả phí hàng tháng." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 9: Vos Communications
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>Vos Communications, Inc.—Current Openings</b><br><br>Vos Communications, Inc. (VCI), is headquartered in Johannesburg, with a print division in Cape Town and a digital media division in Pretoria. We produce scientific publications with a focus on health and wellness in Africa and have been expanding rapidly in the three years following our launch. To meet our current needs, we are seeking applicants with a solid understanding of the medical communications industry for the following positions:<br><br><b>Senior Medical Writer</b><br>Develops original print materials. Requirements include a master’s degree in clinical medicine, at least five years of experience as a medical writer, excellent communication skills, and the ability to work both independently and collaboratively. The successful candidate will be based in our print division.<br><br><b>Assistant Editor</b><br>Works as a member of the Editorial Panel in our print division. Requirements include a bachelor’s degree in journalism or related field, excellent copyediting skills, and experience using editing software.<br><br><b>Medical Writer/Quality Control Reviewer</b><br>Works closely with other members of the print division team to ensure the accuracy of all print division publications. Based in our print division.<br><br>Applicants should submit a cover letter, a résumé, and a writing sample to Mr. Leon Madisha at lmadisha@vci.co.za. Interviews will be conducted from 7 through 12 May at our headquarters, at which time three letters of recommendation must be presented. Only candidates selected for an interview will be contacted.",
            
            "<b>To:</b> Leon Madisha &lt;lmadisha@vci.co.za&gt;<br><b>From:</b> Amina Buys &lt;abuysam@mailworks.net.za&gt;<br><b>Date:</b> 1 May<br><b>Subject:</b> Assistant editor position<br><b>Attachment:</b> buys_application_materials<br><br>Dear Mr. Madisha,<br><br>I am writing to express my interest in the assistant editor position.<br><br>I hold a bachelor’s degree in communications from the University of Richards Bay. I have been working as an editorial assistant at Luxor Publishing House in Durban for six years. My position has enabled me to develop long-term collaborative relationships with clients.<br><br>I believe my experience in the publishing industry and attentiveness to detail make me a perfect fit. Attached please find the relevant application materials. Incidentally, I will be attending a conference near your headquarters at the time of the scheduled interview period, so if I do get selected, getting to the interview will not be a problem.<br><br>Sincerely,<br>Amina Buys"
        ],
        questions: [
            { text: "What is indicated about VCI?", options: { A: "It has been in operation for three years.", B: "It currently has jobs available in various cities.", C: "Its publications center around issues of finance.", D: "Its staff is dedicated to improving its publications." }, correct: "A", explanation: "Quảng cáo ghi 'expanding rapidly in the three years following our launch' -> Công ty đã hoạt động được 3 năm." },
            { text: "In the advertisement, the word 'solid' in paragraph 1, line 4, is closest in meaning to", options: { A: "hard", B: "constant", C: "thorough", D: "dense" }, correct: "C", explanation: "Từ 'solid' trong 'solid understanding' (hiểu biết vững chắc) đồng nghĩa với 'thorough' (cặn kẽ, thấu đáo)." },
            { text: "Which qualification is required by all the job openings?", options: { A: "An ability to work as part of a team", B: "A master's degree in a science field", C: "Strong software skills", D: "A medical background" }, correct: "A", explanation: "Cả 3 vị trí đều yêu cầu làm việc nhóm: Senior ('collaboratively'), Assistant ('member of the Editorial Panel'), QC ('Works closely with other members')." },
            { text: "What most likely was NOT an application document submitted by Ms. Buys?", options: { A: "An illustration of her writing capabilities", B: "An expression of her interest for the job", C: "A description of her qualifications and experience", D: "An employer's evaluation of her abilities and knowledge" }, correct: "D", explanation: "Thư giới thiệu / đánh giá của sếp cũ (employer's evaluation) chỉ được yêu cầu mang tới khi đi phỏng vấn. Lúc nộp hồ sơ qua email thì chưa cần gửi." },
            { text: "Where will Ms. Buys attend a conference?", options: { A: "In Cape Town", B: "In Durban", C: "In Johannesburg", D: "In Pretoria" }, correct: "C", explanation: "Amina nói sẽ dự hội nghị gần trụ sở chính (headquarters). Đoạn 1 ghi trụ sở chính nằm ở Johannesburg." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 10: Stellar Chocolates
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>KENT (26 February)</b>—Stellar Chocolates is a local business offering a wide selection of handcrafted delicacies. With two shops in Kent, the business is well-known in the area. Recently, however, Stellar Chocolates gained national recognition by earning top awards from the Chocolate Council last month.<br><br>Stephanie Davidson, who co-owns the shops with Brian Markus, emphasises the sources and quality of Stellar Chocolates. “Before launching the business, Brian and I spent several months traveling to areas of the world known for quality cacao-bean production. We inspected the plants and learned about traditional harvesting and roasting processes,” she said. In fact, production started only after the co-owners had secured the finest ingredients for their products. They now incorporate a variety of other ingredients such as chili, basil, and even wasabi, to create a unique line of chocolates.<br><br>Demand for Stellar’s line has continued to grow, and the firm expects to open a third shop in Bath later this year. Ms. Davidson noted that they have found additional space in an old mill to be converted for retail use. “The new shop will be our largest, and we plan to establish a mail-order business so that we can ship not just domestically, but also internationally,” she said.",
            
            "<b>http://www.stellarchocolates.co.uk/reviews</b><br><br><b>CUSTOMER REVIEWS</b><br><br>Today I visited the new Stellar Chocolates shop that opened a few weeks ago in the former mill, expecting to see an ordinary candy store. What a surprise! I was delighted to taste some free samples while watching the chocolates being made by hand. I even had a chance to chat with one of the owners, who told me about the origin of their business. She met her co-owner ten years ago in a class at university, and they came up with the business idea for an assignment. They got such positive comments from their professor and fellow students that they decided to turn their idea into a career project. I look forward to many future visits, as the shop is just around the corner from my home.<br><br>— Cynthia Ragusa"
        ],
        questions: [
            { text: "What is stated about Stellar Chocolates in the article?", options: { A: "It sells a variety of items in addition to chocolates.", B: "It does most of its business through mail orders.", C: "It has been recognized for excellence in chocolate making.", D: "It has recently automated its manufacturing process." }, correct: "C", explanation: "Bài báo viết: 'gained national recognition by earning top awards from the Chocolate Council' -> Được công nhận nhờ sự xuất sắc trong việc làm socola." },
            { text: "What is indicated about Mr. Markus?", options: { A: "He was interviewed for the article.", B: "He is a frequent customer.", C: "He met Ms. Davidson at university.", D: "He oversaw the conversion of the mill." }, correct: "C", explanation: "Đoạn review viết về cuộc trò chuyện với Davidson: 'She met her co-owner ten years ago in a class at university'. Người đồng sở hữu (co-owner) chính là Brian Markus." },
            { text: "In the article, the word 'finest' in paragraph 2, line 11, is closest in meaning to", options: { A: "healthiest", B: "best", C: "thinnest", D: "most common" }, correct: "B", explanation: "Từ 'finest' (tinh túy nhất, ngon nhất) trong câu 'secured the finest ingredients' đồng nghĩa với từ 'best' (tốt nhất)." },
            { text: "What is suggested about Ms. Ragusa?", options: { A: "She seldom eats chocolate.", B: "She used to work in a mill in Kent.", C: "She is a colleague of Ms. Davidson's.", D: "She lives in Bath." }, correct: "D", explanation: "Khách hàng Ragusa đến thăm cửa hàng mới mở trong 'former mill' (cối xay cũ) và nói cửa hàng ở ngay góc nhà. Bài báo cho biết cửa hàng trong cối xay này được mở ở 'Bath'. Suy ra cô ấy sống ở Bath." },
            { text: "What is indicated about the newest Stellar Chocolates shop?", options: { A: "Its opening was delayed.", B: "Its hours have been extended.", C: "It is located in a former post office.", D: "It offers complimentary samples." }, correct: "D", explanation: "Khách hàng Ragusa nhắc đến việc được nếm thử socola miễn phí: 'delighted to taste some free samples'. (complimentary = free)." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 11: Tech Support
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>WORK ORDER: 7549</b><br><br><b>Requester:</b> Xi, Gina<br><b>Date Entered:</b> Thursday, 9 April<br><b>Date Due:</b> Friday, 10 April<br><b>Type:</b> Technology end-user request<br><b>Summary:</b> Voice-mail security settings<br><b>Technician Assigned:</b> Arnold, Sam<br><b>Computer Workstation ID:</b> HYS31<br><br><b>Description:</b><br>Is it possible to remove the new layers of security on my voice mail in the new phone system? I really don’t want to use a password, and I certainly don’t want to change it every month. I don’t need a high degree of security because my work is not confidential. If someone else gained access to my messages, it wouldn’t do much harm.",
            
            "<b>To:</b> Gina Xi<br><b>From:</b> Sam Arnold<br><b>Date:</b> Thursday, 10 April<br><b>Subject:</b> Tech support request 7549<br><br>Hello, Ms. Xi,<br><br>This is in reference to your work order 7549 related to the new phone system. I am happy to help you with that. I understand that you do not feel that a high degree of security is needed for your voice-mail settings, but the new system does require you to have a password to retrieve your voice mail. However, company policy allows me to change the settings for employees who do not work with confidential material. I can update the security settings so that you do not have to reset the password on a regular basis.<br><br>I want to make sure that you understand the risk involved with a lower level of security. Anyone who gains access to your voice-mail account can do more than simply listen to your messages. They would be able to delete messages, change your greeting, or change your password so that you would lose access to your own voice mail (at least until someone here at IT could override the password change). If you still feel comfortable with that level of risk, let me know, and I will change the settings so that your password never expires.<br><br>Sam Arnold<br>Tech Support Associate"
        ],
        questions: [
            { text: "What does Ms. Xi’s request indicate about the company?", options: { A: "It provides mobile phones to some employees.", B: "Its employees value confidentiality.", C: "It has recently changed its phone system.", D: "It offers technology training to employees." }, correct: "C", explanation: "Trong yêu cầu, cô Xi hỏi: 'remove the new layers of security on my voice mail in the new phone system?' -> Công ty gần đây đã thay đổi hệ thống điện thoại." },
            { text: "In the e-mail, the word “regular” in paragraph 1, line 6, is closest in meaning to", options: { A: "periodic", B: "orderly", C: "customary", D: "legitimate" }, correct: "A", explanation: "Từ 'regular' trong cụm 'reset the password on a regular basis' mang nghĩa là thay đổi mật khẩu một cách định kỳ (periodic)." },
            { text: "Where did Mr. Arnold learn about the details of Ms. Xi’s request?", options: { A: "In a weekly managers’ meeting", B: "In a work order", C: "In a phone call", D: "In a personal voice mail" }, correct: "B", explanation: "Arnold viết trong email: 'This is in reference to your work order 7549...' -> Anh ấy biết qua phiếu yêu cầu công việc (work order)." },
            { text: "How does Mr. Arnold try to satisfy Ms. Xi’s request?", options: { A: "By agreeing to everything Ms. Xi asked for.", B: "By resetting the password on Ms. Xi’s phone.", C: "By referring the matter to another technician.", D: "By proposing to fulfill only part of Ms. Xi’s request." }, correct: "D", explanation: "Cô Xi muốn gỡ hoàn toàn mật khẩu. Nhưng Arnold nói hệ thống bắt buộc phải có mật khẩu, anh chỉ có thể giúp cô ấy cài đặt để mật khẩu không bao giờ hết hạn. -> Anh ấy chỉ đáp ứng được một phần yêu cầu (fulfill only part)." },
            { text: "What does Mr. Arnold ask Ms. Xi to do?", options: { A: "Make the needed changes to her voice-mail system.", B: "Attend training about the new voice-mail system.", C: "Confirm that she wants him to change her voice-mail system.", D: "Provide a clear description of the problem with her voice-mail system." }, correct: "C", explanation: "Arnold kết luận: 'If you still feel comfortable with that level of risk, let me know, and I will change the settings...' -> Yêu cầu cô xác nhận lại là có thực sự muốn đổi cài đặt hay không." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 12: Rimerko Games
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>E-mail</b><br><b>To:</b> Linda Hanshu<br><b>From:</b> Cliff Merson<br><b>Subject:</b> Lighting Issue<br><b>Date:</b> September 4, 10:12 A.M.<br><br>Hi, Ms. Hanshu:<br><br>I want to check on the issue we discussed about lighting in the latest chapter of Titan Adventure. In past versions of the game, getting the reflections and lighting in green and blue areas correct has been a particular challenge, and it was a problem that kept arising. As the new release, Neptune’s Voyage, is primarily an underwater adventure, addressing this problem is crucial. You said you would take charge of this, and I hope to hear that you have found a solution to the problem. The team was hoping to have one last rendering of the lighting for the game by October 10 for a preliminary run-through. Will the final version of the lighting be ready by then?<br><br>All other aspects of the game are on schedule. Please send me an update about the lighting at your earliest convenience.<br><br>Regards,<br>Cliff Merson<br>Project Manager, Rimerko Games",
            
            "<b>Review of Titan Adventure: Neptune’s Voyage</b><br><b>By Leo Weber, April 1</b><br><br>This new installment of Titan Adventure will surprise and delight both new players and old aficionados long familiar with the series. Though open-world formats have been widespread in recent years, Neptune’s Voyage brings something new to the format. By stripping down instructional guides, the game gives users the opportunity to discover new areas and devices. In Neptune’s Voyage, you wake up as Thetis, a dolphin that is tasked with rescuing Neptune from an underwater cave. Users then climb, run, ride, sail, and fly through the world of the game, encountering new towns, ruins, and other creatures along the way. Some of these creatures will be familiar to longtime fans, but there is plenty of novelty as well. This newest version also corrects the green and blue image rendering that was sometimes a problem in earlier installments of Titan Adventure.<br><br>Neptune’s Voyage launches May 5 on Rimerko Clutch and FS5. It is available in English, Korean, Japanese, French, and Spanish."
        ],
        questions: [
            { text: "In the e-mail, what is suggested about Mr. Merson?", options: { A: "He coordinates a game development team.", B: "He is convinced that Titan Adventure is overpriced.", C: "He is a new employee at Rimerko Games.", D: "He will leave on a business trip on October 10." }, correct: "A", explanation: "Chức danh của Cliff Merson dưới email là 'Project Manager' (Quản lý dự án), vì vậy anh ấy là người điều phối nhóm phát triển game." },
            { text: "In the review, what is indicated about Neptune’s Voyage?", options: { A: "It is a major competitor of Titan Adventure.", B: "It features an open-world format.", C: "It is the first video game in a series.", D: "It is Rimerko’s most challenging game." }, correct: "B", explanation: "Bài đánh giá nhắc đến 'Though open-world formats have been widespread... Neptune's Voyage brings something new to the format' -> Trò chơi này sở hữu định dạng thế giới mở (open-world format)." },
            { text: "What can be concluded about Ms. Hanshu?", options: { A: "She wrote the script for Neptune’s Voyage.", B: "She successfully addressed Mr. Merson’s concern.", C: "She won an award for game design.", D: "She is a project manager." }, correct: "B", explanation: "Cliff giao cho Linda xử lý lỗi ánh sáng xanh lá/xanh dương. Bài đánh giá xác nhận lỗi này đã được khắc phục ('corrects the green and blue image rendering'), chứng tỏ cô ấy đã giải quyết thành công nỗi lo của sếp." },
            { text: "What does Mr. Weber find exciting about Neptune’s Voyage?", options: { A: "It has players act in the role of Neptune.", B: "It uses lighting to show players where to navigate.", C: "It introduces a completely new set of characters.", D: "It lets players explore new features without guidance." }, correct: "D", explanation: "Nhà phê bình Leo Weber viết game đã 'stripping down instructional guides' (lược bỏ các hướng dẫn) để người chơi có cơ hội tự khám phá ('discover new areas and devices')." },
            { text: "When will Neptune’s Voyage be available?", options: { A: "On September 4", B: "On October 10", C: "On April 1", D: "On May 5" }, correct: "D", explanation: "Cuối bài đánh giá có ghi rõ game sẽ chính thức phát hành (launches) vào ngày 5 tháng 5." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 13: Thompson and Groves
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>Thompson and Groves</b><br><br>The law firm of Thompson and Groves is seeking a dedicated assistant to join our established environmental litigation team.<br><br>This assistant will work on a wide range of legal services, such as<br>- investigating evidence related to cases being prepared for court;<br>- preparing exhibits, charts, and diagrams to display information; and<br>- communicating with clients and keeping files updated.<br><br>The best candidate for this position<br>- is self-directed, responsible, and capable of juggling many projects at once; and<br>- has strong communication, organization, and computer skills.<br><br>To apply, e-mail your résumé to Julia Powell (in human resources), julia.powell@thompsonandgroves.com, by May 25. Interviews will be conducted at the beginning of June, and our selection will be made in early July.",
            
            "<b>To:</b> julia.powell@thompsonandgroves.com<br><b>From:</b> jonas_ivanov@sidmail.com<br><b>Date:</b> July 12<br><b>Subject:</b> Re: Legal assistant position<br><br>Dear Ms. Powell,<br><br>I was pleased to read your letter offering me the position of legal assistant. However, after much consideration, I have decided that now is not the best time to leave Wilson Law. I did not realize how deeply I am invested in working on my projects here until I was faced with the possibility of leaving the company. While I was thrilled by the idea of working for an illustrious law firm that has so many high-profile environmental cases, now is not the time for me to make a change.<br><br>It was a pleasure meeting you and your colleagues, and I hope we cross paths in the future.<br><br>Kind regards,<br>Jonas Ivanov"
        ],
        questions: [
            { text: "What is included in the job advertisement?", options: { A: "A brief history of the Thompson and Groves law firm", B: "Directions to a company’s office", C: "A description of the job’s pay and benefits", D: "A description of the ideal applicant" }, correct: "D", explanation: "Quảng cáo liệt kê các tiêu chí cho 'The best candidate for this position' (Ứng viên tốt nhất cho vị trí này) như tự chủ, có trách nhiệm, kỹ năng tốt -> Đây là mô tả về ứng viên lý tưởng." },
            { text: "What most likely is one of Ms. Powell’s job responsibilities?", options: { A: "Preparing exhibits and charts", B: "Updating computer files", C: "Hiring new employees", D: "Writing about environmental issues" }, correct: "C", explanation: "Julia Powell làm việc ở bộ phận nhân sự (human resources) và là người tiếp nhận hồ sơ ứng tuyển, nên cô ấy phụ trách việc tuyển dụng nhân viên mới." },
            { text: "What does Mr. Ivanov indicate in his e-mail?", options: { A: "He has changed his career goals.", B: "He has decided to stay at his present job.", C: "He has decided to retire.", D: "He will apply for a different job." }, correct: "B", explanation: "Anh ấy viết 'now is not the best time to leave Wilson Law' (bây giờ không phải lúc tốt nhất để rời Wilson Law) -> Điều này cho thấy anh ấy sẽ tiếp tục ở lại công ty hiện tại." },
            { text: "What does the e-mail mention about the Thompson and Groves law firm?", options: { A: "It is well-known for its successes.", B: "It will be moving to a larger space.", C: "It no longer specializes in environmental issues.", D: "It will be hosting an international conference." }, correct: "A", explanation: "Ivanov gọi công ty này là 'illustrious law firm' (công ty luật danh tiếng) với nhiều vụ án nổi bật -> Chứng tỏ công ty này nổi tiếng vì những thành công của mình." },
            { text: "What is suggested about Mr. Ivanov?", options: { A: "He received a promotion in May.", B: "He met with Ms. Powell in June.", C: "He and Ms. Powell have a mutual friend.", D: "He has just completed a certification program." }, correct: "B", explanation: "Theo quảng cáo, các cuộc phỏng vấn diễn ra vào đầu tháng 6 (beginning of June). Trong email (gửi tháng 7), Ivanov nói 'It was a pleasure meeting you' (Rất vui được gặp bạn), suy ra anh ấy đã tham gia phỏng vấn và gặp bà Powell vào tháng 6." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 14: Kildare Recreation Centre (Bài Mới)
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>MEMO</b><br><b>To:</b> Kildare Recreation Centre Staff<br><b>From:</b> Madeline Byrne<br><b>Date:</b> 11 April<br><b>Subject:</b> Daily Passes<br><br>As discussed in April’s staff meeting, we are considering raising the cost of daily passes from €5 to €9. The exact increase will be decided in our May meeting. This change is expected to bring in an extra €5,000 over the next year, which we will use toward the cost of replacing our outdoor running track. With the increased revenue from the fee change, we will be close to the €7,000 needed for the improvement.<br><br>I realize that the outdoor running season is short, and I know that in our meeting, some staff members wanted to consider other uses for the money. The possibilities of using the funds for a remodeled reception area, a new floor for the dance studio, or more flat-screen televisions throughout the centre were raised. However, the board of directors thought it would be wiser to focus on the improvement most frequently requested by our members. The upgrades suggested by the staff fall into the €1,000–€2,000 range, and we hope to be able to consider them in the coming years.",
            
            "<b>NOTICE</b><br><b>Kildare Recreation Centre Visitors</b><br><br>Effective 1 June, the cost of a daily pass for nonmembers will be €8. This modest increase will allow us to provide visitors with a much better outdoor running track. The cost of monthly and annual memberships has not changed. Please visit the registration office during regular business hours to discuss membership-related issues."
        ],
        questions: [
            { text: "What is the purpose of the memo?", options: { A: "To announce an increase in membership numbers", B: "To explain how certain funds will be used", C: "To describe tasks to be done for an event", D: "To solicit donations for a project" }, correct: "B", explanation: "Memo giải thích rằng khoản tiền thu thêm (€5,000) từ việc tăng giá vé sẽ được dùng cho việc thay mới đường chạy ngoài trời (outdoor running track)." },
            { text: "What did the staff do at the April meeting?", options: { A: "They designed a survey for recreation center members.", B: "They objected to a price increase.", C: "They proposed upgrades to a recreation center.", D: "They considered moving a reception area." }, correct: "C", explanation: "Đoạn 2 ghi: 'some staff members wanted to consider other uses... possibilities of using the funds for a remodeled reception area...' -> Các nhân viên đã đề xuất những cách nâng cấp khác cho trung tâm." },
            { text: "According to the memo, what do the recreation center members most frequently ask for?", options: { A: "A remodeled reception area", B: "A new dance studio floor", C: "Additional flat-screen televisions", D: "An improved outdoor running track" }, correct: "D", explanation: "Ban giám đốc chọn 'improvement most frequently requested by our members' (cải tiến được hội viên yêu cầu nhiều nhất), và việc được chọn chính là đường chạy ngoài trời (outdoor running track)." },
            { text: "In the notice, the word “modest” in paragraph 1, line 2, is closest in meaning to", options: { A: "shy", B: "modern", C: "creative", D: "small" }, correct: "D", explanation: "Từ 'modest' trong 'modest increase' (mức tăng khiêm tốn) đồng nghĩa với từ 'small' (nhỏ)." },
            { text: "What is true about the new fee for daily passes for nonmembers?", options: { A: "It is less than what was originally considered.", B: "It will be effective starting May 1.", C: "It can be paid online.", D: "It was approved at a June meeting." }, correct: "A", explanation: "Trong Memo (viết trước), dự kiến tăng giá lên €9. Nhưng trong Notice (thông báo chính thức), giá chỉ tăng lên €8. Vì vậy, mức giá mới này thấp hơn mức dự kiến ban đầu." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 15: Central Art Museum (Bài Mới)
    // ==========================================
    {
        type: "Double Passage",
        texts: [
            "<b>Central Art Museum</b><br><b>Upcoming Special Exhibits</b><br><br><b>Worldwide Fashion</b><br>November 1–28<br>Discover how clothing and accessories have changed throughout time in various parts of the world. See clothing samples, historical items, and sketches.<br><br><b>Jeffrey Lamb: Naturalist</b><br>December 1–29<br>Scientist Jeffrey Lamb spent his life studying and taking pictures of wildlife on six continents. See photos of animals and landscapes from the researcher’s personal collection, taken during his forty-year career.<br><br><b>Humans in Art</b><br>January 1–29<br>This collection of paintings and sculptures from dozens of artists, past and present, shows us the many ways artists can depict a human subject. Works from both famous and relatively unknown artists are included here.<br><br><b>Everyday Art</b><br>February 1–26<br>A variety of handmade items are on display in this exhibit showing art in everyday life. From handmade quilts to furniture, see these household items in a whole new way.",
            
            "<b>Review of Central Art Museum</b><br><b>Reviewer:</b> Mary Walsh<br><b>Stars:</b> ★★★★★<br><br>I recommend the Central Art Museum to anyone interested in not only art but history as well. I’ve made two trips to the museum recently. My first trip was with my school’s photography club. We only saw the special exhibit featuring photography, but I left wanting to see the rest of the museum. I returned a few days later and had the chance to walk through the entire museum. Each exhibit was different but full of interesting pieces. Be sure to stop at the interactive room near the gift shop for a hands-on experience. During my first trip, the room had cameras with fun backgrounds. Visitors took pictures of themselves, and for a small fee, I got a printout of myself as if I were holding a flag on the moon! Like the special exhibits, the activities at the interactive room change every month, so you will always find something new and interesting to do."
        ],
        questions: [
            { text: "According to the schedule, what would a visitor most likely see at the first special exhibit?", options: { A: "Shoes", B: "Furniture", C: "Radios", D: "Paintings" }, correct: "A", explanation: "Triển lãm đầu tiên là Worldwide Fashion (quần áo, phụ kiện). Trong các đáp án, chỉ có Shoes (giày) là một loại phụ kiện." },
            { text: "What is indicated about the special exhibit in February?", options: { A: "It includes mostly paintings done by local artists.", B: "It will end before the other exhibits listed on the Web site.", C: "Visitors may see items similar to those that they have in their homes.", D: "It has returned to the museum after a popular earlier appearance." }, correct: "C", explanation: "Triển lãm tháng 2 (Everyday Art) trưng bày các đồ dùng thủ công (handmade quilts, furniture) và được gọi là 'household items' (đồ dùng gia đình). Vì vậy, khách có thể thấy những đồ vật giống như đồ ở nhà mình." },
            { text: "Why did Ms. Walsh go to the museum a second time?", options: { A: "She wanted to take more photographs.", B: "She wanted to see more of the museum.", C: "She accidentally left an item at the museum.", D: "She got a discount on a ticket." }, correct: "B", explanation: "Sau chuyến đi đầu tiên, cô ấy viết: 'I left wanting to see the rest of the museum' -> Cô ấy muốn xem nốt phần còn lại của bảo tàng." },
            { text: "What does Ms. Walsh recommend that readers do?", options: { A: "Take a guided tour of the museum", B: "Call the museum for more information", C: "Buy something at the museum gift shop", D: "Participate in an activity at the museum" }, correct: "D", explanation: "Cô ấy khuyên người đọc: 'Be sure to stop at the interactive room... for a hands-on experience' -> Tham gia các hoạt động trực tiếp (trải nghiệm thực tế) tại bảo tàng." },
            { text: "What exhibit did Ms. Walsh visit on the first trip to the museum?", options: { A: "Worldwide Fashion", B: "Jeffrey Lamb: Naturalist", C: "Humans in Art", D: "Everyday Art" }, correct: "B", explanation: "Chuyến đầu tiên cô đi cùng câu lạc bộ nhiếp ảnh và xem triển lãm về nhiếp ảnh (special exhibit featuring photography). Nhìn lịch, 'Jeffrey Lamb' trưng bày các bức ảnh thiên nhiên (photos of animals)." }
        ]
    }
];